/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblio.ui.reportes;

import biblio.Files.ObjectRead;
import biblio.Models.Prestamo;
import biblio.ui.FormPrincipal;
import java.io.File;
import java.io.IOException;
import java.time.LocalDate;
import static java.time.temporal.ChronoUnit.DAYS;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gamcas
 */
public class FormLibroMorosos extends javax.swing.JFrame {

    private static LocalDate todayDate = LocalDate.now();
    private static DefaultTableModel model;

    /**
     * Creates new form FormPrestamoLibros
     */
    public FormLibroMorosos() {
        initComponents();
        this.contenedor.setSize(650, 550);
        this.setSize(660, 580);
        this.setLocationRelativeTo(null);
        model = (DefaultTableModel) jTable1.getModel();
        llenarTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        titulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        contenedor.setLayout(null);

        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.black));
        titulo.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Prestamos con Mora");
        titulo.add(jLabel1);
        jLabel1.setBounds(240, 10, 189, 30);

        contenedor.add(titulo);
        titulo.setBounds(0, 0, 680, 50);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.darkGray));
        jPanel1.setLayout(null);

        jTable1.setBackground(new java.awt.Color(0, 153, 153));
        jTable1.setForeground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Estudiante", "Libro", "Fecha de prestamo", "Fecha Acutal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 640, 403);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblio/images/regresar.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(290, 410, 80, 60);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setText("Regresar");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(290, 470, 90, 24);

        contenedor.add(jPanel1);
        jPanel1.setBounds(0, 50, 680, 510);

        getContentPane().add(contenedor, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
        FormPrincipal f = new FormPrincipal();
        f.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    public static void addDatatoJTable(Prestamo prestamo, DefaultTableModel model) {

        try {
            Object rowData[] = new Object[4];

            rowData[0] = prestamo.getCarnetEstudiante();
            rowData[1] = ObjectRead.readLibro(prestamo.getCodigoLibro()).getTitulo();
            rowData[2] = prestamo.getFechaPrestamo();
            rowData[3] = todayDate;
            model.addRow(rowData);
        } catch (IOException ex) {
            Logger.getLogger(FormLibroMorosos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
//limpiamos la tabla de cualquier dato no deseado

    public static void eliminar(DefaultTableModel tb) {
        int a = tb.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            tb.removeRow(tb.getRowCount() - 1);
        }
    }

    private static void llenarTabla() {

        eliminar(model);
        try {

            File f = new File("DB\\prestamos");
//recorremos la carpeta prestamo para obtener los carnet de los estudiantes
            for (String s : f.list()) {
                File fi = new File("DB\\prestamos\\" + s);
                //recorremos cada estudiante
                for (String string : fi.list()) {
                    //obtenemos el nombre del prestamo sin su extencion
                    String comm = string.substring(0, string.indexOf("."));
                    //creamos un objeto prestamo y le asignamos los datos que devuelve el archivo binario
                    Prestamo p = ObjectRead.readPrestamo(Integer.valueOf(s), comm);
//creamos dos fechas la fecha de prestamo y la fecha de hoy
                    LocalDate date = p.getFechaPrestamo();
                    LocalDate date2 = LocalDate.now();
                    //obtenemos los dias entre ambas fechas
                    long days = DAYS.between(date, date2);
                    if (p.getFechaDevolucion() == null) {
//si se cumple agregamos los datos a la tabla
                        if (days > 3) {
                            addDatatoJTable(p, model);
                        }

                    }
                }
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLibroMorosos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLibroMorosos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLibroMorosos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLibroMorosos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLibroMorosos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel titulo;
    // End of variables declaration//GEN-END:variables
}
