/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblio.ui;

import AppPackage.AnimationClass;
import biblio.movimiento.AnimationPanel;
import biblio.ui.reportes.*;

/**
 *
 * @author Gamcas
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
        this.setResizable(false);
        this.setBounds(0, 0, 1000, 720);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPConteiner = new javax.swing.JPanel();
        JPRegistrarPres = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        JPRegistrarLib = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        JTRegistrarNomLib = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        JTAutorLib = new javax.swing.JTextField();
        JTCantCopias = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        JPRegistrarEstu = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        JTNombreEstu = new javax.swing.JTextField();
        JTCarnet = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        JTCodCarrera = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        JPTitulo = new javax.swing.JPanel();
        btnTitulo = new javax.swing.JLabel();
        JPMenu = new javax.swing.JPanel();
        btnRegistrarPres = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRegistrarLib = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRegistrarEstudiante = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        r1 = new javax.swing.JLabel();
        r2 = new javax.swing.JLabel();
        r3 = new javax.swing.JLabel();
        r4 = new javax.swing.JLabel();
        r6 = new javax.swing.JLabel();
        r5 = new javax.swing.JLabel();
        JPInfo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPConteiner.setPreferredSize(new java.awt.Dimension(1000, 700));
        JPConteiner.setLayout(null);

        JPRegistrarPres.setBackground(new java.awt.Color(79, 157, 166));
        JPRegistrarPres.setPreferredSize(new java.awt.Dimension(880, 640));
        JPRegistrarPres.setLayout(null);

        jLabel5.setText("Seleccione a Estudiante:");
        JPRegistrarPres.add(jLabel5);
        jLabel5.setBounds(30, 40, 150, 16);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Carnet", "Nombre", "Carrera"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        JPRegistrarPres.add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 410, 100);

        jLabel10.setText("Seleccione el Libro:");
        JPRegistrarPres.add(jLabel10);
        jLabel10.setBounds(480, 40, 150, 16);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Cantidad disponible"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        JPRegistrarPres.add(jScrollPane2);
        jScrollPane2.setBounds(460, 60, 370, 100);

        jLabel11.setText("Registrar fecha actual:");
        JPRegistrarPres.add(jLabel11);
        jLabel11.setBounds(30, 200, 140, 16);

        jButton3.setText("Fecha actual");
        JPRegistrarPres.add(jButton3);
        jButton3.setBounds(30, 240, 120, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Registrar prestamo del libro");
        JPRegistrarPres.add(jLabel18);
        jLabel18.setBounds(280, 300, 180, 30);

        jButton4.setText("Confirmar");
        JPRegistrarPres.add(jButton4);
        jButton4.setBounds(310, 350, 120, 30);

        JPConteiner.add(JPRegistrarPres);
        JPRegistrarPres.setBounds(1000, 60, 880, 640);

        JPRegistrarLib.setBackground(new java.awt.Color(247, 255, 86));
        JPRegistrarLib.setPreferredSize(new java.awt.Dimension(880, 640));
        JPRegistrarLib.setLayout(null);

        jLabel13.setText("Nombre del Libro:");
        JPRegistrarLib.add(jLabel13);
        jLabel13.setBounds(30, 70, 110, 16);

        JTRegistrarNomLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTRegistrarNomLibActionPerformed(evt);
            }
        });
        JPRegistrarLib.add(JTRegistrarNomLib);
        JTRegistrarNomLib.setBounds(30, 100, 240, 30);

        jLabel12.setText("Codigo del libro:");
        JPRegistrarLib.add(jLabel12);
        jLabel12.setBounds(400, 70, 100, 16);

        jLabel14.setText("Ejem. AAA-000");
        JPRegistrarLib.add(jLabel14);
        jLabel14.setBounds(610, 70, 100, 16);

        jTextField1.setText("jTextField1");
        JPRegistrarLib.add(jTextField1);
        jTextField1.setBounds(400, 100, 150, 30);

        jLabel15.setText("Autor del libro:");
        JPRegistrarLib.add(jLabel15);
        jLabel15.setBounds(30, 180, 110, 16);

        jLabel16.setText("Cantidad de copias:");
        JPRegistrarLib.add(jLabel16);
        jLabel16.setBounds(400, 180, 130, 16);

        JTAutorLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTAutorLibActionPerformed(evt);
            }
        });
        JPRegistrarLib.add(JTAutorLib);
        JTAutorLib.setBounds(30, 210, 240, 30);
        JPRegistrarLib.add(JTCantCopias);
        JTCantCopias.setBounds(400, 210, 150, 30);

        jButton1.setText("Fecha actual");
        JPRegistrarLib.add(jButton1);
        jButton1.setBounds(30, 330, 110, 32);

        jLabel17.setText("Registar fecha actual:");
        JPRegistrarLib.add(jLabel17);
        jLabel17.setBounds(30, 290, 120, 16);

        jButton2.setText("Registrar");
        JPRegistrarLib.add(jButton2);
        jButton2.setBounds(290, 390, 120, 32);

        JPConteiner.add(JPRegistrarLib);
        JPRegistrarLib.setBounds(1000, 60, 880, 640);

        JPRegistrarEstu.setBackground(new java.awt.Color(222, 222, 222));
        JPRegistrarEstu.setPreferredSize(new java.awt.Dimension(880, 640));
        JPRegistrarEstu.setLayout(null);

        jLabel19.setText("Nombre del Estudiante:");
        JPRegistrarEstu.add(jLabel19);
        jLabel19.setBounds(70, 50, 220, 16);

        jLabel20.setText("Carnet:");
        JPRegistrarEstu.add(jLabel20);
        jLabel20.setBounds(550, 50, 70, 16);

        jLabel21.setText("Ejem. 2018*****");
        JPRegistrarEstu.add(jLabel21);
        jLabel21.setBounds(660, 50, 110, 16);

        JTNombreEstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTNombreEstuActionPerformed(evt);
            }
        });
        JPRegistrarEstu.add(JTNombreEstu);
        JTNombreEstu.setBounds(20, 70, 420, 30);

        JTCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTCarnetActionPerformed(evt);
            }
        });
        JPRegistrarEstu.add(JTCarnet);
        JTCarnet.setBounds(550, 70, 220, 30);

        jLabel22.setText("Codigo de carrera:");
        JPRegistrarEstu.add(jLabel22);
        jLabel22.setBounds(70, 160, 140, 16);
        JPRegistrarEstu.add(JTCodCarrera);
        JTCodCarrera.setBounds(80, 190, 70, 30);

        jLabel23.setText("Fecha de Nacimiento:");
        JPRegistrarEstu.add(jLabel23);
        jLabel23.setBounds(380, 160, 140, 16);

        jTextField2.setText("Año/Mes/Dia");
        JPRegistrarEstu.add(jTextField2);
        jTextField2.setBounds(380, 190, 140, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Registrar Estudiante");
        JPRegistrarEstu.add(jButton5);
        jButton5.setBounds(290, 300, 190, 50);

        JPConteiner.add(JPRegistrarEstu);
        JPRegistrarEstu.setBounds(1000, 60, 880, 640);

        JPTitulo.setBackground(new java.awt.Color(200, 218, 211));
        JPTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnTitulo.setText("Biblioteca CUNOC");
        JPTitulo.add(btnTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 340, 40));

        JPConteiner.add(JPTitulo);
        JPTitulo.setBounds(0, 0, 1500, 60);

        JPMenu.setBackground(new java.awt.Color(79, 157, 166));
        JPMenu.setPreferredSize(new java.awt.Dimension(112, 766));
        JPMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrarPres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblio/images/registrar.png"))); // NOI18N
        btnRegistrarPres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarPresMouseClicked(evt);
            }
        });
        JPMenu.add(btnRegistrarPres, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 60, -1));

        jLabel2.setText("Registrar Prestamo");
        JPMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        btnRegistrarLib.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblio/images/12.png"))); // NOI18N
        btnRegistrarLib.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarLibMouseClicked(evt);
            }
        });
        JPMenu.add(btnRegistrarLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 102, -1, -1));

        jLabel3.setText("Registrar libro");
        JPMenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 163, -1, -1));

        btnRegistrarEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblio/images/estudiante.png"))); // NOI18N
        btnRegistrarEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarEstudianteMouseClicked(evt);
            }
        });
        JPMenu.add(btnRegistrarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 188, -1, -1));

        jLabel1.setText("Registar estudiante");
        JPMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblio/images/arch.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        JPMenu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 70, 60));

        jLabel6.setText("Leer archivo");
        JPMenu.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblio/images/reportes.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        JPMenu.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel8.setText("Reportes");
        JPMenu.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 70, -1));
        JPMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 130, -1));
        JPMenu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 130, -1));
        JPMenu.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 130, -1));
        JPMenu.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 130, -1));

        r1.setText("*Prestamos a Entregar");
        r1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r1MouseClicked(evt);
            }
        });
        JPMenu.add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 470, -1, -1));

        r2.setText("*Prestamos con mora");
        r2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r2MouseClicked(evt);
            }
        });
        JPMenu.add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 490, -1, -1));

        r3.setText("*Dinero Recaudado");
        JPMenu.add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 510, -1, -1));

        r4.setText("<html>*Prestamos hechos por estudiante");
        r4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r4MouseClicked(evt);
            }
        });
        JPMenu.add(r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 530, 120, -1));

        r6.setText("<html>*Libros prestados por carrera");
        JPMenu.add(r6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 590, 110, -1));

        r5.setText("*Libros Prestados");
        JPMenu.add(r5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 570, -1, -1));

        JPConteiner.add(JPMenu);
        JPMenu.setBounds(0, 60, 130, 640);

        JPInfo.setPreferredSize(new java.awt.Dimension(880, 640));
        JPInfo.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblio/images/portada.jpg"))); // NOI18N
        JPInfo.add(jLabel9);
        jLabel9.setBounds(110, 50, 600, 90);

        JPConteiner.add(JPInfo);
        JPInfo.setBounds(130, 60, 870, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPConteiner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPConteiner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarPresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarPresMouseClicked
        AnimationPanel.jPanelXRight(120, 1000, 5, 5, JPInfo);
        AnimationPanel.jPanelXRight(120, 1000, 5, 5, JPRegistrarEstu);
        AnimationPanel.jPanelXRight(120, 1000, 5, 5, JPRegistrarLib);
        AnimationPanel.jPanelXLeft(1000, 120, 5, 5, JPRegistrarPres);
        btnTitulo.setText("Registrar Prestamo");
    }//GEN-LAST:event_btnRegistrarPresMouseClicked

    private void btnRegistrarLibMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarLibMouseClicked
        AnimationPanel.jPanelXRight(120, 1000, 5, 5, JPInfo);
        AnimationPanel.jPanelXRight(120, 1000, 5, 5, JPRegistrarPres);
        AnimationPanel.jPanelXRight(120, 1000, 5, 5, JPRegistrarEstu);
        AnimationPanel.jPanelXLeft(1000, 120, 5, 5, JPRegistrarLib);
        btnTitulo.setText("Registrar Nuevo Libro");
    }//GEN-LAST:event_btnRegistrarLibMouseClicked

    private void JTRegistrarNomLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTRegistrarNomLibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTRegistrarNomLibActionPerformed

    private void JTAutorLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTAutorLibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTAutorLibActionPerformed

    private void btnRegistrarEstudianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarEstudianteMouseClicked
        AnimationPanel.jPanelXRight(120, 1000, 5, 5, JPInfo);
        AnimationPanel.jPanelXRight(120, 1000, 5, 5, JPRegistrarPres);
        AnimationPanel.jPanelXRight(120, 1000, 5, 5, JPRegistrarLib);
        AnimationPanel.jPanelXLeft(1000, 120, 5, 5, JPRegistrarEstu);
        btnTitulo.setText("Registrar Nuevo Estudiante");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarEstudianteMouseClicked

    private void JTNombreEstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTNombreEstuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTNombreEstuActionPerformed

    private void JTCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTCarnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTCarnetActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        FormLecturaArchivo f = new FormLecturaArchivo();
        this.dispose();
        f.setVisible(true);


    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked

        moverDerecha();
        moverIzq();

    }//GEN-LAST:event_jLabel7MouseClicked

    private void r1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r1MouseClicked
        FormPrestamoLibros f = new FormPrestamoLibros();
        this.dispose();
        f.setVisible(true);
    }//GEN-LAST:event_r1MouseClicked

    private void r2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r2MouseClicked
        FormLibroMorosos f = new FormLibroMorosos();
        this.dispose();
        f.setVisible(true);
    }//GEN-LAST:event_r2MouseClicked

    private void r4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r4MouseClicked
        FormPrestamosEstudiantes f = new FormPrestamosEstudiantes();
        this.dispose();
        f.setVisible(true);
    }//GEN-LAST:event_r4MouseClicked

    private void moverDerecha() {
        AnimationClass a = new AnimationClass();
        a.jLabelXRight(-200, 0, 5, 5, r1);
        a.jLabelXRight(-200, 0, 5, 5, r2);
        a.jLabelXRight(-200, 10, 5, 5, r3);
        a.jLabelXRight(-200, 10, 5, 5, r4);
        a.jLabelXRight(-200, 10, 5, 5, r5);
        a.jLabelXRight(-200, 10, 5, 5, r6);
    }

    private void moverIzq() {
        AnimationClass a = new AnimationClass();
        a.jLabelXLeft(0, -200, 5, 5, r1);
        a.jLabelXLeft(0, -200, 5, 5, r2);
        a.jLabelXLeft(10, -200, 5, 5, r3);
        a.jLabelXLeft(10, -200, 5, 5, r4);
        a.jLabelXLeft(10, -200, 5, 5, r5);
        a.jLabelXLeft(10, -200, 5, 5, r6);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FormPrincipal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPConteiner;
    private javax.swing.JPanel JPInfo;
    private javax.swing.JPanel JPMenu;
    private javax.swing.JPanel JPRegistrarEstu;
    private javax.swing.JPanel JPRegistrarLib;
    private javax.swing.JPanel JPRegistrarPres;
    private javax.swing.JPanel JPTitulo;
    private javax.swing.JTextField JTAutorLib;
    private javax.swing.JTextField JTCantCopias;
    private javax.swing.JTextField JTCarnet;
    private javax.swing.JTextField JTCodCarrera;
    private javax.swing.JTextField JTNombreEstu;
    private javax.swing.JTextField JTRegistrarNomLib;
    private javax.swing.JLabel btnRegistrarEstudiante;
    private javax.swing.JLabel btnRegistrarLib;
    private javax.swing.JLabel btnRegistrarPres;
    private javax.swing.JLabel btnTitulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel r1;
    private javax.swing.JLabel r2;
    private javax.swing.JLabel r3;
    private javax.swing.JLabel r4;
    private javax.swing.JLabel r5;
    private javax.swing.JLabel r6;
    // End of variables declaration//GEN-END:variables
}
