/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblio.ui;

import biblio.Files.TextRead;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author Gamcas
 */
public class FormLecturaArchivo extends javax.swing.JFrame {

    /**
     * Creates new form FormLecturaArchivo
     */
    public FormLecturaArchivo() {
        initComponents();

        this.setSize(624, 468);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        btnAnalizar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        btnAnalizar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCargar = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(624, 50));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Lectura Archivo");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(240, 10, 150, 24);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel2.setLayout(null);

        areaTexto.setColumns(20);
        areaTexto.setEditable(false);
        areaTexto.setRows(5);
        jScrollPane1.setViewportView(areaTexto);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 630, 300);

        btnAnalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblio/images/analizar.png"))); // NOI18N
        btnAnalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnalizarMouseClicked(evt);
            }
        });
        jPanel2.add(btnAnalizar);
        btnAnalizar.setBounds(270, 300, 80, 60);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("Analizar Archivo");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(240, 360, 150, 20);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("Cargar Archivo");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 360, 131, 20);

        btnCargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblio/images/carga.png"))); // NOI18N
        btnCargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCargarMouseClicked(evt);
            }
        });
        jPanel2.add(btnCargar);
        btnCargar.setBounds(50, 300, 80, 60);

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblio/images/regresar.png"))); // NOI18N
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        jPanel2.add(btnRegresar);
        btnRegresar.setBounds(480, 300, 80, 60);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setText("Regresar");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(480, 360, 90, 24);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnalizarMouseClicked

        new TextRead(path).start();
        btnCargar.setVisible(true);
        btnAnalizar.setVisible(false);

    }//GEN-LAST:event_btnAnalizarMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        if (JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del sistema?",
                "Salir del sistema", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnCargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargarMouseClicked
        areaTexto.setText("");
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());

        int returnValue = jfc.showOpenDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jfc.getSelectedFile();
            path = selectedFile.getAbsolutePath();
            btnAnalizar.setVisible(true);
            btnCargar.setVisible(false);
            
            areaTexto.append("Se Analizara el archivo: " + path + "\n" + "\n");

        }
    }//GEN-LAST:event_btnCargarMouseClicked

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked

        File estudiante = new File("DB\\estudiantes");
        File libro = new File("DB\\prestamos");
        String[] listadoEst = estudiante.list();
        String[] listadoLibro = libro.list();

        if ((listadoEst == null || listadoEst.length == 0)
                && (listadoLibro == null || listadoLibro.length == 0)) {
            JOptionPane.showMessageDialog(null, "OH!, al parecer la base de datos esta vacia.\n"
                    + "Por favor ingrese datos al sistema mediante un archivo");
            System.out.println("No hay elementos dentro de la carpeta actual");

        } else {
            FormPrincipal f = new FormPrincipal();
            f.setVisible(true);
            f.setLocationRelativeTo(null);
            this.dispose();
        }

    }//GEN-LAST:event_btnRegresarMouseClicked

    private String path;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea areaTexto;
    private javax.swing.JLabel btnAnalizar;
    private javax.swing.JLabel btnCargar;
    private javax.swing.JLabel btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
